Add EOmaps package
matplotlib/mpl-third-party pull request #101
Opened 2021-12-13 17:48 UTC by raphaelquast

## PR Summary

2021-12-13 18:32 UTC, story645 commented
Your package looks so cool, thanks for adding it!

2021-12-14 00:23 UTC, story645 requested changes

2021-12-14 00:23 UTC, story645 commented on packages/eomaps.yml
> +keywords:  interactive mapping
This should be a list

2021-12-14 08:03 UTC, raphaelquast commented on packages/eomaps.yml
> +keywords:  interactive mapping
should be fixed

2021-12-14 08:05 UTC, jklymak commented on packages/eomaps.yml
> +site: https://github.com/raphaelquast/EOmaps
```suggestion
site: https://raphaelquast.github.io/EOmaps/ 
```
?  We already link the repo...

2021-12-14 08:13 UTC, jklymak commented
No, we automatically detect the badges, and we don't deal with those other ones.  (ahem, left over from the project where we copied this ;-)

2021-12-14 08:14 UTC, merged

2021-12-14 08:14 UTC, jklymak commented
I squashed when I merged, just in case you are tracking commits for some reason ;-) Thanks for the addition!

2021-12-14 08:15 UTC, raphaelquast commented
awesome, thanks for merging!