add mpl-point-picker
matplotlib/mpl-third-party pull request #73
Opened 2021-06-30 22:16 UTC by ianhi

## PR Summary
Adds https://mpl-point-clicker.readthedocs.io/en/stable/

2021-06-30 22:38 UTC, story645 approved these changes

2021-07-01 00:46 UTC, QuLogic requested changes
picker or clicker? Seems to be the latter, but that's not what's in/the name of the file.

2021-07-01 00:58 UTC, ianhi commented
> picker or clicker? Seems to be the latter, but that's not what's in/the name of the file.

woops I've leaked out a bit of the superposition in my mental model of the name. Name i settled on is `clicker` will psuh update. thanks for the catch!

2021-07-01 01:53 UTC, QuLogic approved these changes

2021-07-01 01:53 UTC, merged